name: pkswallet
description: A wallet that leverages Account Abstraction and allows users sign SAFE multi-sig transactions with biometrics, HDkey and Private keys

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  go_router: ^11.1.2
  gradients: ^0.1.1+2
  flutter_svg: ^2.0.7
  simple_shadow: ^0.3.1
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/bitcoin.png
    - assets/curve_line.svg
    - assets/rectangle.svg
    - assets/rec.png
    - assets/30.svg
    - assets/curve.svg
    - assets/star.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/static/Inter-Black.ttf
        - asset: assets/fonts/static/Inter-ExtraBold.ttf
        - asset: assets/fonts/static/Inter-Bold.ttf
        - asset: assets/fonts/static/Inter-Medium.ttf
        - asset: assets/fonts/static/Inter-Regular.ttf
        - asset: assets/fonts/static/Inter-SemiBold.ttf
        - asset: assets/fonts/static/Inter-Thin.ttf
        - asset: assets/fonts/static/Inter-Light.ttf


  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
